# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

silent: true

tasks:
  new:
    cmds:
      - npx zenn new:article --emoji 🌿 --published false
    desc: '新しい記事を追加'

  preview:
    cmds:
      - open http://localhost:8000
      - npx zenn preview
    desc: 'コンテンツのプレビュー'

  textlint:
    cmds:
      - npx textlint -f pretty-error {{.CLI_ARGS}}
    ignore_error: true
    desc: 'textlintの実行（個別）'

  textlint-all:
    cmds:
      - npx textlint -f pretty-error articles/
    ignore_error: true
    desc: '全ての記事に対してtextlintを実行'

  textlint-fix:
    cmds:
      - npx textlint --fix {{.CLI_ARGS}}
    ignore_error: true
    desc: 'textlintで修正（個別）'

  textlint-fix-all:
    cmds:
      - npx textlint --fix articles/
    ignore_error: true
    desc: '全ての記事をtextlintで修正'

