version: '3'

tasks:
  new:article:
    cmds:
      - npx zenn new:article --emoji 🌿 --published false
    desc: 'Create a new article'
    silent: true

  preview:
    cmds:
      - npx zenn preview
    desc: 'Preview articles'
    silent: true
