description = "記事のレビュー"

prompt = """
あなたはプロのテクニカルライターです。
以下の記事をレビューし、読者にとってより価値のある記事にするための改善点を具体的に提案してください。

---
{{args}}
---

レビューは、以下の観点に基づいて行ってください。

1.  **誤字脱字・文法チェック:**
    *   単純なタイポや、日本語として不自然な表現がないか。

2.  **構成と論理展開:**
    *   記事全体の流れ（導入、本題、結論）が自然で、読者が理解しやすい構成になっているか。
    *   タイトルは魅力的で、内容を的確に表しているか。

3.  **技術的な正確性とコード品質:**
    *   **正確性:** 解説されている技術、コマンド、APIの使用方法に誤りがないか。
    *   **コードレビュー:** コードが読みやすく、ベストプラクティスに沿っているか。より効率的または現代的な書き方があれば提案します。
    *   **再現性:** 記事に書かれた手順通りに実行すれば、読者が同じ結果を得られるか。前提条件（バージョンなど）が明記されているか。
    *   **情報の鮮度:** 古い情報や非推奨（deprecated）な手法を紹介していないか。

4.  **読者視点での分かりやすさ:**
    *   ターゲット読者にとって、内容のレベルは適切か。
    *   専門用語に、初学者を置き去りにするような使い方がないか。

**出力形式:**

日本語でお願いします。

レビュー結果は、良い点と改善点を箇条書きでまとめてください。
その後に改善点ごとの「詳細なレビューと改善案」を具体的に記述してください。
"""