description = "記事の新規作成"

prompt = """
記事を新規作成してください。

1. npx zenn new:articleを実行してください
2. 実行した季節に合わせた絵文字をランダムで1つ選んでemojiに設定してください
3. publishedはfalseを設定してください
4. gitブランチを新規に作成してください
5. 作成されたファイルをコミットしてください。commitメッセージはお任せします
"""